# Generated by Django 4.1.4 on 2023-01-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_material',
            name='measure',
            field=models.CharField(choices=[('kg', 'kg'), ('gram', 'gram'), ('litre', 'litre'), ('millilitre', 'millilitre')], max_length=60, null=True),
        ),
    ]
