# Generated by Django 4.1.5 on 2023-01-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0008_product_manufactured_quantity'),
        ('rawmaterial', '0002_raw_material_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_material',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manu.product'),
        ),
    ]
