# Generated by Django 4.1.5 on 2023-01-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactured_product', models.CharField(blank=True, max_length=20, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='manufacturing',
            old_name='created_at',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='manufacturing',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='manufacturing',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='manufacturing',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manu.product'),
        ),
    ]
