# Generated by Django 4.1.5 on 2023-01-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0003_remove_product_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturing',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
