# Generated by Django 4.1.5 on 2023-01-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0005_sellproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
