# Generated by Django 4.1.5 on 2023-01-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0006_sellproduct_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturing',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='sellproduct',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manu.product'),
        ),
    ]
