# Generated by Django 4.1.5 on 2023-01-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0007_rename_name_manufacturing_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
