# Generated by Django 4.1.5 on 2023-01-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0008_product_manufactured_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturing',
            name='total_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
