# Generated by Django 4.1.5 on 2023-01-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0009_manufacturing_total_charge_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturing',
            name='total_charge_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='total_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
