# Generated by Django 4.1.5 on 2023-01-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0010_remove_manufacturing_total_charge_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sell_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
