# Generated by Django 4.1.5 on 2023-01-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0011_product_total_sell_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproduct',
            name='total_sell_amount',
        ),
    ]
