# Generated by Django 4.1.5 on 2023-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0012_remove_sellproduct_total_sell_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
