# Generated by Django 4.1.5 on 2023-01-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0013_product_sub_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_manufactured_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_sell_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
