# Generated by Django 4.1.5 on 2023-01-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0017_alter_manufacturing_charges_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='raw_material_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
