# Generated by Django 4.1.5 on 2023-01-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0022_remove_product_sub_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sell_status_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
