# Generated by Django 4.1.5 on 2023-01-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0025_alter_product_manufactured_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturing',
            name='charges_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
