# Generated by Django 4.1.5 on 2023-01-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0026_alter_manufacturing_charges_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_pro_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('profit', 'profit'), ('loss', 'loss')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price_manu_product',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
