# Generated by Django 4.1.5 on 2023-01-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0027_product_price_pro_loss_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_sell_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
