# Generated by Django 4.1.4 on 2023-01-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
        ('manu', '0028_alter_product_sub_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.customer'),
        ),
    ]
