# Generated by Django 4.1.4 on 2023-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0029_sellproduct_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellproduct',
            name='status_Sell',
            field=models.CharField(choices=[('New', 'New'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='New', max_length=80),
        ),
    ]
