# Generated by Django 4.1.4 on 2023-01-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0031_alter_product_manufactured_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproduct',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
