# Generated by Django 4.1.5 on 2023-02-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0032_sellproduct_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('kg', 'kg'), ('gram', 'gram'), ('litre', 'litre'), ('millilitre', 'millilitre')], default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='type_name',
            field=models.CharField(blank=True, choices=[('Manufactured_product', 'Manufactured_product'), ('Buy_product', 'Buy_product')], max_length=20, null=True),
        ),
    ]
