# Generated by Django 4.1.4 on 2023-01-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manu', '0018_product_raw_material_amount'),
        ('rawmaterial', '0003_raw_material_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_pro_fromshop', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(blank=True, choices=[('profit', 'profit'), ('loss', 'loss')], max_length=100, null=True)),
                ('price_pro_loss', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('org_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manu.product')),
            ],
        ),
    ]
