# Generated by Django 4.1.5 on 2023-02-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_customer_created_at_customer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
